source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JZtvOSParallaxButton_Example', :exclusive => true do
  pod "JZtvOSParallaxButton", :path => "../"
end

target 'JZtvOSParallaxButton_Tests', :exclusive => true do
  pod "JZtvOSParallaxButton", :path => "../"

  
end
