source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JZtvOSParallaxButtom_Example', :exclusive => true do
  pod "JZtvOSParallaxButtom", :path => "../"
end

target 'JZtvOSParallaxButtom_Tests', :exclusive => true do
  pod "JZtvOSParallaxButtom", :path => "../"

  
end
